name: Expo CI/CD - SafeRide

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Setup Node and Expo
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx expo doctor

  web_build_and_deploy:
    name: Build & Deploy Web to Firebase
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Expo Web
        run: npx expo export:web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"

  expo_qr:
    name: Generate QR for Expo Go
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Start Expo Server (background)
        run: npx expo start --tunnel &
      
      - name: Generate QR Code
        run: npx expo qr:show
